# Docker Compose for All-At-Once Code Clone Detection

version: "3.8"
services:
  clone-detector:
    image: cljdetector
    build: ./Containers/cljdetector
    command: clear
    ports:
      - "8087:3000"
    volumes:
      - ./Containers/cljdetector:/usr/src/app
      - qc-volume:/QualitasCorpus
    environment:
      DBHOST: dbstorage
      SOURCEDIRtest: "/usr/src/app/test/data"
      SOURCEDIReclipse: "/QualitasCorpus/QualitasCorpus-20130901r/Systems/eclipse_SDK"
      SOURCEDIR: "/QualitasCorpus"
      CHUNKSIZE: 20
    depends_on:
      - dbstorage

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - "27019:27017"
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

  monitor-tool:
    image: monitor
    build: ./Containers/MonitorTool
    ports:
      - "8501:8501"
    environment:
      DBHOST: dbstorage
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLE_IPV6: "false"   # ✅ IMPORTANT FIX
    depends_on:
      - dbstorage

volumes:
  dbstorage:
  dbconfig:
  qc-volume:
    external: true
